=== tanykoo/tany-jpos/src/main/java/com/tany/jpos/xml/ISO8583.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema  xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.tanykoo.iso8583" elementFormDefault="qualified">

    <xs:element name="ISO8583">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="msg" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="head">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="field" minOccurs="0" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="body">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="field" minOccurs="1" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:element name="field">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="maxlen" type="xs:string"/>
                    <xs:attribute name="fieldno" type="xs:string"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== tanykoo/tany-jpos/src/main/java/com/tany/jpos/xml/ISO8583.xml
<?xml version="1.0" encoding="UTF-8" ?>
<ISO8583 xmlns="http://www.tanykoo.iso8583"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.tanykoo.iso8583 ISO8583.xsd">

    <msg id="C034">
        <head>
        </head>
        <body>
            <field fieldno="adsd" maxlen="31"/>
        </body>
    </msg>
    
    <msg>
        <head></head>
        <body>
            <field>SDSFS</field>
        </body>
    </msg>
</ISO8583>

=== tanykoo/tany-jpos/src/main/resource/com/tany/jpos/xml/ISO8583.xml
<?xml version="1.0" encoding="UTF-8" ?>
<ISO8583 xmlns="http://www.tanykoo.iso8583"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.tanykoo.iso8583 ISO8583.xsd">

    <msg id="C034">
        <head>
        </head>
        <body>
            <field fieldno="1" maxlen="31" name="ad"/>
            <field fieldno="2" maxlen="31" name="asd"/>
        </body>
    </msg>
    
    <msg id="C035">
        <head></head>
        <body>
            <field fieldno="3" maxlen="3" name="ds"/>
            <field fieldno="2" maxlen="32" name="ds"/>
        </body>
    </msg>
</ISO8583>
